"""Outbreak records (single source of truth for outbreaks.json / outbreaks.csv).

Every number below was transcribed on 2026-10-01 from the primary source named in `sources`
(full text via Europe PMC open-access XML saved under notes/fulltext/, the publisher page, an
accepted-manuscript PDF, or -- where stated -- the abstract only). `access` records which.
Counts are *secondary* cases among exposed persons excluding the index case(s) unless stated.
`derived` lists every field that is NOT printed in the source but computed/inferred here.
None means "not reported in the sources accessed" (never a guess).

quality grades:
  A  = single-source exposure, exposed denominator enumerated, seat/zone-level positions,
       geometry and duration reported (ventilation measured or estimated);
  B  = denominator and duration reported, partial geometry or spatial information;
  C  = aggregate / multi-generation / abstract-only / denominator incomplete;
  X  = outside the model's scope (large shared settings recorded for reference only).
"""

RECORDS = [
    # ------------------------------------------------------------------ OFFICE
    dict(
        id="O1_seoul_callcentre", scene="office", analogue=False,
        setting="Call centre, 11th floor of a 19-storey mixed-use building (open-plan desks)",
        location="Seoul, South Korea", event_dates="2020-02-21..2020-03-08 (building closed 2020-03-09)",
        pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="park2020", doi="10.3201/eid2608.201274", access="full text (Europe PMC OA XML) + Fig. 1/2 images (EID)")],
        exposure_type="repeated daily co-working, multi-generation (onsets 25 Feb - 20 Mar on 11th floor)",
        exposure_duration_h=None, exposure_duration_note="working days over ~2 weeks; hours per day not reported",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None,
        geometry_note="Scaled floor plan published (Fig. 2) but no scale bar or area; 199 workstation desks digitized in two wings (137 north, 62 south) plus un-digitized east offices",
        occupancy_n=216, ventilation="not reported (an 'evaluation of ventilation system' is marked on the epidemic curve but no results are given)",
        masks="not reported", index_case="unknown; first 11th-floor onset 25 Feb 2020; an earlier 10th-floor case had onset 22 Feb",
        n_exposed=216, n_infected=94, includes_index=True,
        attack_rate_reported="43.5% (95% CI 36.9-50.4%)",
        spatial_pattern="'Most of the case-patients on the 11th floor were on the same side of the building'. Digitized Fig. 2: 79/137 desks marked as case seats in north wing vs 4/62 in south wing, 1 in east offices (84 marked seats vs 94 reported cases).",
        other_groups="Other floors: 7th 0/182, 8th 0/207, 9th 1/206, 10th 2/27, floors 1-6 0/84, residents 0/201. Household SAR 34/225 (15.1%); 34/210 (16.2%) for symptomatic index.",
        spatial_data_files=["data/park2020_callcentre_seats_digitized.csv", "data/park2020_callcentre_epicurve_digitized.csv"],
        quality="B",
        quality_notes="Attack rate denominators complete (99.8% tested). No room size, no ventilation, no hours. Seat map shows only 84 of 94 case seats; desk occupancy assumed 1 per desk. Multi-generation: not a single-source event.",
        derived=["seat-level counts by wing (image digitization)", "epidemic curve counts (image digitization)"],
    ),
    dict(
        id="O2_zurich_office", scene="office", analogue=False,
        setting="13-person team in a 700 m2 open-plan office (team occupies about one quarter) + 30 m2 conference room",
        location="Canton of Zurich, Switzerland", event_dates="2020-03 (index onset 2020-03-10)",
        pathogen="SARS-CoV-2 (ancestral); index co-infected with adenovirus-4",
        sources=[dict(key="weissberg2020", doi="10.1186/s13756-020-00861-z", access="full text (Europe PMC OA XML)")],
        exposure_type="single index, ~1.5 working days incl. a 1-h team meeting with singing",
        exposure_duration_h=11.0, exposure_duration_note="index spent ~8 h presymptomatic + ~3 h oligosymptomatic with the team",
        room_dimensions="open-plan office 700 m2 (team area ~1/4); conference room 30 m2",
        floor_area_m2=175.0, ceiling_height_m=None, volume_m3=None,
        geometry_note="workstations a minimum of 0.8 m apart; seating plan in Fig. 1 of source",
        occupancy_n=13, ventilation="mechanical; 'air renewal within 1 hour' in open office (~1 ACH), within 15 min in conference room (~4 ACH); no recirculation",
        masks="none", index_case="1 team member (E1)",
        n_exposed=12, n_infected=8, n_infected_alt=10, includes_index=False,
        attack_rate_reported="index 'directly infected 67 to 83% of teammates' (8 or potentially 10 of 12); 11 of 13 team members ill overall",
        spatial_pattern="whole team affected; no gradient analysable (n=12, frequent shared-desk work, 5-min daily huddle)",
        other_groups="household attack rate 39% (95% CI 17-64)", spatial_data_files=[], quality="B",
        quality_notes="Small n. Close-contact behaviour (shared keyboards, huddles, singing) confounds distance. 8 vs 10 secondary cases depends on generation assignment.",
        derived=["floor_area_m2 = 700/4", "attack rate bounds 8/12 and 10/12"],
    ),
    dict(
        id="O3_england_office", scene="office", analogue=False,
        setting="Public-facing public-sector office: three large open-plan offices over three storeys",
        location="England, UK", event_dates="2021-08..2021-09", pathogen="SARS-CoV-2 (Delta period; vaccinated workforce)",
        sources=[dict(key="nicholls2024", doi="10.1093/occmed/kqad100", access="abstract only (Europe PMC)")],
        exposure_type="multi-week workplace outbreak, multi-generation", exposure_duration_h=None, exposure_duration_note="weeks",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note=None,
        occupancy_n=40, ventilation="'deemed adequate using carbon dioxide monitoring (typically <=1000 ppm)'",
        masks="not reported in abstract", index_case="not reported in abstract",
        n_exposed=40, n_infected=22, includes_index=True, attack_rate_reported="55% (22/40 workers)",
        spatial_pattern="surface contamination concentrated in a small shared security office (6/9 samples positive)",
        other_groups=None, spatial_data_files=[], quality="C",
        quality_notes="Abstract only; denominators include index; no geometry. Useful as a contrast: adequate ventilation + vaccination and still 55%.",
        derived=[],
    ),
    dict(
        id="O4_german_meatplant", scene="office", analogue=True,
        setting="Beef-processing line, fixed work stations on a conveyor line (indoor workplace analogue with seat-like fixed positions)",
        location="Rheda-Wiedenbrueck, Germany", event_dates="2020-05 (index worked three consecutive early shifts)",
        pathogen="SARS-CoV-2 (clade 20C)",
        sources=[dict(key="guenther2020", doi="10.15252/emmm.202013296", access="full text (Europe PMC OA XML); Appendix tables not retrieved")],
        exposure_type="single index, 3 consecutive shifts", exposure_duration_h=None, exposure_duration_note="3 shifts (shift length not stated; breaks 2x30 min + 1 h)",
        room_dimensions="processing line ~32 m x 8.5 m inside a 2,800 m2, 6.1 m high hall",
        floor_area_m2=272.0, ceiling_height_m=6.1, volume_m3=None,
        geometry_note="distance of every fixed-position worker from the index plotted in source Fig. 3A (not digitized)",
        occupancy_n=147, ventilation="air exchange rate < 1 per h for the hall; unfiltered recirculating cooling fans, ~10 C",
        masks="not stated as worn at the line in the text accessed", index_case="1 worker (B1), asymptomatic when tested",
        n_exposed=78, n_infected=20, includes_index=False,
        attack_rate_reported="20/78 = 25.6% among workers with fixed stations around the index; '>60% of co-workers within a distance of 8 m' (counts in Appendix Table S2)",
        spatial_pattern="Spatial over-representation of cases maximal within an 8 m radius of the index (P = 2.3e-5); infection rates highest closest to the index.",
        other_groups="whole early shift: 18 positive of 140 tested on 25 May + 11 more in follow-up among 147 workers", spatial_data_files=[], quality="B",
        quality_notes="Counts within 8 m not transcribed (appendix). Cold, recirculated air and heavy physical work: extrapolation to offices is qualitative only.",
        derived=["floor_area_m2 = 32 x 8.5"],
    ),
    dict(
        id="O5_tb_office", scene="office", analogue=True,
        setting="Office building, co-workers of a cavitary tuberculosis case (classic Wells-Riley calibration)",
        location="USA (Massachusetts)", event_dates="reported 1991", pathogen="Mycobacterium tuberculosis",
        sources=[dict(key="nardell1991", doi="10.1164/ajrccm/144.2.302", access="abstract only (Europe PMC)")],
        exposure_type="single index, ~4 weeks of co-working", exposure_duration_h=160.0, exposure_duration_note="'estimated 4-wk exposure'; 160 h assumes 40 h/week",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note=None,
        occupancy_n=68, ventilation="~15 cfm (7 L/s) outdoor air per occupant; CO2 ~1000 ppm",
        masks="none", index_case="1 co-worker", n_exposed=67, n_infected=27, includes_index=False,
        attack_rate_reported="27/67 (40%) tuberculin conversions", spatial_pattern="not reported in abstract",
        other_groups=None, spatial_data_files=[], quality="C",
        quality_notes="Different pathogen (obligate airborne). Abstract only. Included because it is the canonical office-scale calibration of the Wells-Riley equation that defines the quantum.",
        derived=["exposure_duration_h = 4 weeks x 40 h", "occupancy_n = 67 + index"],
    ),
    # ------------------------------------------------------------- SUPERMARKET
    dict(
        id="S1_liaocheng_supermarket", scene="supermarket", analogue=False,
        setting="Supermarket (employees vs customers)", location="Liaocheng, Shandong, China", event_dates="2020-01..2020-02",
        pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="tian2021", doi="10.1186/s12889-021-10713-z", access="full text (Europe PMC OA XML)")],
        exposure_type="employees: repeated daily shifts (multi-day); customers: single short visits",
        exposure_duration_h=None, exposure_duration_note="not reported (customer dwell time not measured)",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note=None,
        occupancy_n=None, ventilation="not reported", masks="not reported",
        index_case="not identified with certainty; first-generation cases were employees",
        n_exposed=120, n_infected=11, includes_index=True,
        attack_rate_reported="employees 9.2% (11/120); customers 0/8224 screened; total screened 8437",
        spatial_pattern="none reported", other_groups="customers 0/8224; relatives/friends 13/93 (14.0%)",
        spatial_data_files=[], quality="B",
        quality_notes="Best available supermarket record: both employee and customer denominators. No geometry, no dwell times; the 11 employee cases include the unidentified primary case(s). Customer screening completeness not stated.",
        derived=[],
    ),
    dict(
        id="S2_tianjin_dept_store", scene="supermarket", analogue=True,
        setting="Department store (retail floor, sales staff vs customers)", location="Baodi District, Tianjin, China",
        event_dates="2020-01-20..2020-01-26 (store closed 26 Jan)", pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="chen2020tianjin", doi="10.1016/j.ajic.2020.06.006", access="full text (Europe PMC OA XML)"),
                 dict(key="li2022twoclusters", doi="10.3390/ijerph19084876", access="full text (Europe PMC OA XML)"),
                 dict(key="jiang2021deptstore", doi="10.1007/s11783-021-1386-6", access="abstract (Europe PMC)")],
        exposure_type="staff: daily shifts over ~1 week; customers: single visits during Spring Festival shopping",
        exposure_duration_h=None, exposure_duration_note="not reported",
        room_dimensions="'approximately 3400 m2'", floor_area_m2=3400.0, ceiling_height_m=None, volume_m3=None, geometry_note=None,
        occupancy_n=None, ventilation="described as 'a poorly ventilated public place' (no measurement)", masks="not reported",
        index_case="not identified", n_exposed=194, n_infected=6, n_infected_alt=7, includes_index=True,
        attack_rate_reported="no attack rate printed; staff cases 6 (Li 2022) or 7 (Chen 2020); 'approximately 200 employees', 194 employees isolated",
        spatial_pattern="none reported",
        other_groups="customer cases 23 (Li 2022) or 21 (Chen 2020), customer denominator unknown; 43-60 cases linked in total depending on cut-off date",
        spatial_data_files=[], quality="C",
        quality_notes="Sources disagree on counts (6 vs 7 staff; 21 vs 23 customers; 43 vs 60 linked cases). Customer denominator absent, so no customer attack rate can be formed. Staff attack rate is DERIVED here.",
        derived=["staff attack rate = 6/194 (or 7/194)"],
    ),
    dict(
        id="S3_wenzhou_mall", scene="supermarket", analogue=True,
        setting="Shopping mall, 8 floors; office on floor 7 plus retail floors B1-6", location="Wenzhou, Zhejiang, China",
        event_dates="2020-01 (mall closed 22 Jan)", pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="cai2020", doi="10.3201/eid2606.200412", access="full text (Europe PMC OA XML)")],
        exposure_type="multi-day, mixed staff/customers, indirect contact", exposure_duration_h=None, exposure_duration_note="not reported",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note=None,
        occupancy_n=None, ventilation="not reported", masks="not reported", index_case="uncertain (patient A, returned from Wuhan 18 Dec 2019)",
        n_exposed=None, n_infected=None, includes_index=None,
        attack_rate_reported="no denominators: 7 cases in one floor-7 office, 7 mall staff (floors B1-3), 10 customers, 11 close contacts",
        spatial_pattern="cases on several floors without direct contact; shared restrooms/elevators",
        other_groups=None, spatial_data_files=[], quality="C",
        quality_notes="Case series without denominators: cannot be used for attack rates; documents that retail transmission to customers occurs.",
        derived=[],
    ),
    dict(
        id="S4_boston_grocery", scene="supermarket", analogue=False,
        setting="Single grocery retail store, employees (cross-sectional PCR screen)", location="Massachusetts, USA", event_dates="2020-05",
        pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="lan2021", doi="10.1136/oemed-2020-106774", access="abstract only (Europe PMC)")],
        exposure_type="occupational, cumulative; point prevalence not an attack rate", exposure_duration_h=None, exposure_duration_note=None,
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note=None,
        occupancy_n=None, ventilation="not reported", masks="not reported in abstract", index_case="none (community + workplace acquisition not separable)",
        n_exposed=104, n_infected=21, includes_index=True,
        attack_rate_reported="21/104 (20%) PCR-positive; customer-facing roles OR 5.1 (95% CI 1.1-24.8)",
        spatial_pattern="risk gradient by role (customer-facing vs not), not by position", other_groups=None, spatial_data_files=[], quality="C",
        quality_notes="Point prevalence in a high-incidence community; not attributable to in-store transmission. Use only as an upper bound on staff infection.",
        derived=[],
    ),
    # --------------------------------------------------------------- CLASSROOM
    dict(
        id="C1_marin_classroom", scene="classroom", analogue=False,
        setting="Elementary-school classroom, 24 students in 5 rows, teacher reading aloud unmasked", location="Marin County, California, USA",
        event_dates="2021-05-17..2021-05-21 (teacher symptomatic from 19 May)", pathogen="SARS-CoV-2 Delta (B.1.617.2)",
        sources=[dict(key="lamhine2021", doi="10.15585/mmwr.mm7035e2", access="full text (Europe PMC OA XML)")],
        exposure_type="single index (teacher), repeated over <=5 school days (2 days while symptomatic)",
        exposure_duration_h=None, exposure_duration_note="school days 17-21 May; hours in class not reported",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None,
        geometry_note="five rows; 'all desks were separated by 6 ft' (1.83 m); seating chart in Fig. 1 of source",
        occupancy_n=25, ventilation="portable HEPA filter in room; doors and windows left open", masks="students masked (high adherence); teacher unmasked when reading aloud",
        index_case="1 unvaccinated teacher", n_exposed=24, n_infected=12, includes_index=False,
        attack_rate_reported="12/22 tested (55%); '50%' of 24 students; front two rows 8/10 (80%) vs back three rows 4/14 (28%), Fisher p = 0.036",
        spatial_pattern="monotone decrease with distance from the teacher's desk (two zones reported)",
        other_groups="second classroom (different grade) 6/14 tested; 4 siblings, 4 parents; 27 cases in total",
        spatial_data_files=[], quality="A",
        quality_notes="2 of 24 students untested (counted as non-cases in the row analysis). Row-level, not seat-level, numbers in text. Exposure hours not given. Children; Delta variant.",
        derived=[],
    ),
    dict(
        id="C2_jerusalem_highschool", scene="classroom", analogue=False,
        setting="High school (grades 7-12), crowded classrooms 35-38 students in 39-49 m2", location="Jerusalem, Israel",
        event_dates="2020-05-18..2020-05-27 (heatwave + mask exemption 19-21 May)", pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="steinzamir2020", doi="10.2807/1560-7917.ES.2020.25.29.2001352", access="full text (Europe PMC OA XML)")],
        exposure_type="two unlinked index students, ~8 school days, multi-class mixing", exposure_duration_h=None, exposure_duration_note="~8-9 school days at 6.3-6.7 h per day (38-40 h per 6-day week)",
        room_dimensions="class area 39-49 m2 (1.1-1.3 m2 per student)", floor_area_m2=44.0, ceiling_height_m=None, volume_m3=None,
        geometry_note="floor_area_m2 is the midpoint of the reported range", occupancy_n=37,
        ventilation="split air-conditioning per class running continuously (recirculating); windows not described", masks="exempted 19-21 May",
        index_case="2 students (not epidemiologically linked)", n_exposed=1161, n_infected=153, includes_index=True,
        attack_rate_reported="students 153/1161 (13.2%); staff 25/151 (16.6%); by grade: 7th 40/197, 8th 34/197, 9th 61/187, 10th 9/200, 11th 6/195, 12th 3/188",
        spatial_pattern="strong clustering by class: 20 cases in one 9th-grade class, 13 each in two others, 14 in one 7th-grade class",
        other_groups="staff 25/151", spatial_data_files=["data/spatial_strata.csv"], quality="B",
        quality_notes="School-level denominators; per-class denominators only as class size range (35-38). Multi-generation over 10 days. No within-room positions.",
        derived=["floor_area_m2 midpoint", "occupancy_n midpoint of 35-38 + 0 (students only)"],
    ),
    dict(
        id="C3_utah_elementary", scene="classroom", analogue=False,
        setting="20 elementary schools, classrooms with seats a median 3 ft (0.9 m) apart, masks worn", location="Salt Lake County, Utah, USA",
        event_dates="2020-12-03..2021-01-31", pathogen="SARS-CoV-2 (pre-Alpha)",
        sources=[dict(key="hershow2021", doi="10.15585/mmwr.mm7012e3", access="full text (Europe PMC OA XML)")],
        exposure_type="51 index patients (40 students, 11 staff), school-day exposure of classroom contacts",
        exposure_duration_h=None, exposure_duration_note="school days during infectious period; not quantified",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note="median seat spacing 3 ft",
        occupancy_n=None, ventilation="not quantified in text accessed", masks="86% observed student mask use",
        index_case="51 index patients", n_exposed=728, n_infected=5, includes_index=False,
        attack_rate_reported="0.7% (5/728 tested susceptible school contacts); 1041 contacts, 735 tested, 12 cases of which 5 school-associated",
        spatial_pattern="5 cases in 5 separate classrooms; no outbreaks (>=2 linked cases) detected",
        other_groups=None, spatial_data_files=[], quality="B",
        quality_notes="Pooled over 51 index cases: a per-index classroom secondary attack rate, the right quantity for a negative control. 70.6% of contacts tested.",
        derived=[],
    ),
    dict(
        id="C4_measles_school", scene="classroom", analogue=True,
        setting="Suburban elementary school, 14 classrooms sharing a recirculating ventilation system", location="upstate New York, USA",
        event_dates="spring 1974", pathogen="measles virus",
        sources=[dict(key="riley1978", doi="10.1093/oxfordjournals.aje.a112560", access="abstract only (Europe PMC)")],
        exposure_type="single index (2nd-grade girl), first generation", exposure_duration_h=None, exposure_duration_note="not in abstract",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note=None, occupancy_n=None,
        ventilation="high percentage of recirculated air (central system)", masks="none", index_case="1 student",
        n_exposed=None, n_infected=28, includes_index=False,
        attack_rate_reported="28 secondary cases in 14 different classrooms; 60 cases after two further generations; 97% of children vaccinated; index emitted ~93 quanta/min",
        spatial_pattern="secondary cases spread over 14 classrooms (not confined to the index's home room) -> building-scale airborne mixing",
        other_groups=None, spatial_data_files=[], quality="C",
        quality_notes="Abstract only: susceptible denominators not transcribed, so no attack rate. It is the origin of the quantum concept [riley1978airborne].",
        derived=[],
    ),
    dict(
        id="C5_cheonan_fitness", scene="classroom", analogue=True,
        setting="Fitness dance classes, 5-22 students in a ~60 m2 room, 50 min intense exercise", location="Cheonan, South Korea",
        event_dates="2020-02-15..2020-03-09", pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="jang2020", doi="10.3201/eid2608.200633", access="full text (Europe PMC OA XML)")],
        exposure_type="8 infected instructors teaching classes twice weekly for ~1 week", exposure_duration_h=0.83,
        exposure_duration_note="50 min per class, 2 classes per week",
        room_dimensions="'room ~60 m2'", floor_area_m2=60.0, ceiling_height_m=None, volume_m3=None, geometry_note=None, occupancy_n=None,
        ventilation="not reported", masks="none", index_case="8 instructors infected at a 4-h workshop on 15 Feb",
        n_exposed=217, n_infected=57, includes_index=False,
        attack_rate_reported="26.3% (95% CI 20.9-32.5%) among 217 students exposed in 12 facilities",
        spatial_pattern="none within rooms; no cases in classes with <5 participants or in low-intensity (Pilates/yoga) classes of 7-8 in the same room",
        other_groups="secondary attack rate among 830 close contacts 4.10%", spatial_data_files=[], quality="B",
        quality_notes="n_infected = 57 is DERIVED from 26.3% x 217 (count not printed in main text). High-exertion breathing: an upper-range analogue for classrooms.",
        derived=["n_infected = round(0.263*217)"],
    ),
    # ---------------------------------------------------- METRO / CARRIAGE
    dict(
        id="T1_zhejiang_bus", scene="metro", analogue=True,
        setting="Coach bus, 15 rows (3+2 seats), air conditioning in recirculation/heating mode", location="Ningbo, Zhejiang, China",
        event_dates="2020-01-19", pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="shen2020", doi="10.1001/jamainternmed.2020.5225", access="publisher's full-text page (JAMA Netw) as an automated text extraction; abstract via Europe PMC")],
        exposure_type="single index, single day, two 50-min rides", exposure_duration_h=100 / 60, exposure_duration_note="50 min each way",
        room_dimensions="15 rows, row pitch 0.75 m (measured)", floor_area_m2=None, ceiling_height_m=None, volume_m3=None,
        geometry_note="index in middle seat of the 3-seat side, row 8; seat map in source figure (not digitized)",
        occupancy_n=68, ventilation="air conditioning on indoor recirculation; 4 openable windows (2 per side)", masks="none",
        index_case="1 passenger (pre-symptomatic)", n_exposed=67, n_infected=23, includes_index=False,
        attack_rate_reported="24/68 = 35.3% incl. index; 23/67 = 34.3% excl. index",
        spatial_pattern="No significant distance gradient: rows 5-11 (within ~2 m) 14/33 vs other rows 9/34, RR 1.6 (0.8-3.2); rows 6-10 11/23 vs others 12/44, RR 1.8 (0.9-3.3). Window-side passengers (3-seat side) and those near the door largely spared.",
        other_groups="unexposed bus 1: 0/60; other attendees of the same 150-min outdoor event: 7/172 (4.1%)",
        spatial_data_files=["data/spatial_strata.csv"], quality="A",
        quality_notes="Natural control group (bus 1). Exposure also includes the shared worship event (controlled for by 7/172). Bus dimensions not printed.",
        derived=[],
    ),
    dict(
        id="T2_hunan_coach", scene="metro", analogue=True,
        setting="Long-distance coach, 11.3 m x 2.5 m, 49 seats, windows closed", location="Hunan, China (Changsha to city D)",
        event_dates="2020-01-22", pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="luo2020", doi="10.1093/ofid/ofaa430", access="full text (Europe PMC OA XML)"),
                 dict(key="ou2022", doi="10.1016/j.buildenv.2021.108414", access="full text (Europe PMC OA XML)")],
        exposure_type="single index (pre-symptomatic), single ride", exposure_duration_h=2.5,
        exposure_duration_note="2.5 h (Luo 2020); 200 min, 12:10-15:30 (Ou 2022)",
        room_dimensions="11.3 m x 2.5 m (Luo 2020); air volume 60.42 m3 (Ou 2022)", floor_area_m2=28.25, ceiling_height_m=None, volume_m3=60.42,
        geometry_note="index in second rear row (Luo) ; seat-numbered plan in Ou 2022 Fig. 2 (not digitized)",
        occupancy_n=49, ventilation="measured time-averaged 1.72 L/s per person (Ou 2022); 0.62 ACH when idling", masks="none among secondary cases",
        index_case="1 passenger", n_exposed=48, n_infected=7, includes_index=False,
        attack_rate_reported="Luo 2020: pooled 9/(48+12) = 15.0% (95% CI 6-24%) over both vehicles; Ou 2022: 7/46 = 15.2% on this coach",
        spatial_pattern="No distance gradient: rear rows 8-13 3/19 (15.8%) vs front rows 1-7 4/26 (15.4%); driver side 6/24 vs opposite side 1/20 (Ou 2022). Farthest infectees ~4.5 m (7 rows) from index (Luo 2020).",
        other_groups="1 further case on the return trip of the same coach 30 min later (seat near the index's former seat)",
        spatial_data_files=["data/spatial_strata.csv"], quality="A",
        quality_notes="Two investigations of the same event give different denominators (48 vs 46) and durations (150 vs 200 min). Ventilation measured post hoc with tracer gas.",
        derived=["floor_area_m2 = 11.3 x 2.5", "n_exposed uses Luo 2020 (48)"],
    ),
    dict(
        id="T3_hunan_minibus", scene="metro", analogue=True,
        setting="Minibus, 5.5 m x 2.5 m, 18 seats, windows mostly closed", location="Hunan, China", event_dates="2020-01-22",
        pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="luo2020", doi="10.1093/ofid/ofaa430", access="full text (Europe PMC OA XML)"),
                 dict(key="ou2022", doi="10.1016/j.buildenv.2021.108414", access="full text (Europe PMC OA XML)")],
        exposure_type="single index (same person as T2), single ride", exposure_duration_h=1.0, exposure_duration_note="~1 h (60 min)",
        room_dimensions="5.5 m x 2.5 m; air volume 21.69 m3 (Ou 2022)", floor_area_m2=13.75, ceiling_height_m=None, volume_m3=21.69,
        geometry_note=None, occupancy_n=13, ventilation="measured time-averaged 3.22 L/s per person (Ou 2022)", masks="none among secondary cases",
        index_case="1 passenger", n_exposed=12, n_infected=2, includes_index=False,
        attack_rate_reported="2/12 (Luo 2020: '2 out of 12 passengers (including the driver)'); Ou 2022: 2/17 = 11.8%",
        spatial_pattern="infectees 1 row (~1.5 m) and 3 rows (~4.5 m) from the index", other_groups=None,
        spatial_data_files=["data/spatial_strata.csv"], quality="B",
        quality_notes="Denominator differs between the two reports (12 vs 17). Very small n.",
        derived=["floor_area_m2 = 5.5 x 2.5"],
    ),
    dict(
        id="T4_china_hsr", scene="metro", analogue=True,
        setting="High-speed train second-class coaches (3+2 seats per row); pooled contact-tracing cohort", location="China (national G-train network)",
        event_dates="2019-12-19..2020-03-06", pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="hu2021", doi="10.1093/cid/ciaa1057", access="publisher's full-text page (OUP) as an automated text extraction; abstract via Europe PMC")],
        exposure_type="2,334 index patients; co-travel 0.13-13.8 h (mean 2.1 h, SD 1.8)", exposure_duration_h=2.1, exposure_duration_note="mean co-travel time",
        room_dimensions="seat width ~0.5 m; row spacing reported as ~0.4 m", floor_area_m2=None, ceiling_height_m=None, volume_m3=None,
        geometry_note="contacts defined as within 3 rows of the index; 5 column offsets (incl. aisle)", occupancy_n=None,
        ventilation="not reported", masks="not reported", index_case="2,334 index patients",
        n_exposed=72093, n_infected=234, includes_index=False,
        attack_rate_reported="0.32% (95% CI 0.29-0.37%); adjacent seat 3.5% (2.9-4.3%); same row 1.5% (1.3-1.8%); 1/2/3 rows away 0.14/0.18/0.08%; +0.15 %-points per hour overall, +1.3 per hour adjacent",
        spatial_pattern="steep decay within the row (3.53 -> 1.65 -> 0.38% over 1-3 seats) and an order-of-magnitude drop between rows; non-zero plateau ~0.1% at 2-3 rows",
        other_groups="later occupant of the index's seat: 1/1342 (0.075%)", spatial_data_files=["data/hu2021_train_attack_matrix.csv"], quality="A",
        quality_notes="Largest distance-resolved dataset, but cell denominators were not transcribed (percentages + CIs only). Row-0 cell alignment of Table 1 was reconstructed. Early-pandemic ascertainment (symptomatic testing) biases attack rates downward.",
        derived=["alignment of the row-0 cells of Table 1"],
    ),
    dict(
        id="T5_vn54_flight", scene="metro", analogue=True,
        setting="Long-haul flight, business-class cabin (28 seats, 21 occupied)", location="London to Hanoi (VN54)", event_dates="2020-03-01/02",
        pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="khanh2020", doi="10.3201/eid2611.203299", access="full text (Europe PMC OA XML)")],
        exposure_type="single symptomatic index, single flight", exposure_duration_h=10.0, exposure_duration_note="'about 10 hours'",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note="seat map in source Fig. 1",
        occupancy_n=21, ventilation="aircraft cabin (HEPA recirculation; not quantified)", masks="not mandatory, not generally worn",
        index_case="1 business-class passenger (symptomatic)", n_exposed=20, n_infected=12, includes_index=False,
        attack_rate_reported="business class 13/21 = 62% incl. index; '≤2 seats away' 11/12 (92%) vs '>2 seats away' 1/8 (13%), RR 7.3 (1.2-46.2)",
        spatial_pattern="sharp proximity effect within the cabin; no spread to premium economy 0/35; economy 2/145; crew 1/16",
        other_groups="premium economy 0/35; economy 2/145; crew 1/16", spatial_data_files=["data/spatial_strata.csv"], quality="A",
        quality_notes="84% of passengers traced. Economy cases may be unrelated. High air-change cabin: not a carriage, but the only 10-h seat-resolved record.",
        derived=["n_infected excluding index = 13 - 1"],
    ),
    dict(
        id="T6_influenza_airliner", scene="metro", analogue=True,
        setting="Jet airliner held on the ground for 3 h with the ventilation system inoperative", location="Alaska, USA", event_dates="1977-03",
        pathogen="influenza A/Texas/1/77 (H3N2)",
        sources=[dict(key="moser1979", doi="10.1093/oxfordjournals.aje.a112781", access="abstract only (Europe PMC)")],
        exposure_type="single index, single event", exposure_duration_h=3.0, exposure_duration_note="3-h ground delay",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note=None, occupancy_n=54,
        ventilation="none (system inoperative during the delay)", masks="none", index_case="1 passenger",
        n_exposed=None, n_infected=None, includes_index=None,
        attack_rate_reported="'within 72 hours, 72 per cent of the passengers became ill'; attack rate 'varied with the amount of time spent aboard'",
        spatial_pattern="not in abstract", other_groups=None, spatial_data_files=[], quality="C",
        quality_notes="Abstract only: exact numerator/denominator and the time-aboard strata were not transcribed. Other pathogen. Canonical example of duration dose-response in an unventilated cabin.",
        derived=[],
    ),
    dict(
        id="T7_japan_no_train_clusters", scene="metro", analogue=False,
        setting="National cluster surveillance; commuter rail as a venue category", location="Japan", event_dates="2020-01-15..2020-04-04",
        pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="furuse2020", doi="10.3201/eid2609.202272", access="full text (Europe PMC OA XML)")],
        exposure_type="surveillance (clusters of >=5 cases with a common venue)", exposure_duration_h=None, exposure_duration_note=None,
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note=None, occupancy_n=None,
        ventilation=None, masks=None, index_case=None, n_exposed=None, n_infected=None, includes_index=None,
        attack_rate_reported="61 clusters among 3,184 cases: 18 healthcare, 10 other care, 10 restaurants/bars, 8 workplaces, 7 music events, 5 gyms, 2 ceremonies, 1 transport-related (an airplane); no cluster is attributed to trains or stations",
        spatial_pattern="n/a", other_groups=None, spatial_data_files=[], quality="C",
        quality_notes="Absence of detected clusters is weak evidence: exposure on anonymous mass transit is almost never traceable. No documented metro-carriage outbreak with denominators was found in this search.",
        derived=[],
    ),
    # ----------------------------------------------- RESTAURANT / CHOIR ANALOGUES
    dict(
        id="R1_guangzhou_restaurant", scene="restaurant", analogue=True,
        setting="Restaurant dining floor, 18 tables, 89 patrons, fan-coil air conditioning without outdoor air", location="Guangzhou, China",
        event_dates="2020-01-24", pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="li2021", doi="10.1016/j.buildenv.2021.107788", access="full text (Europe PMC OA XML)"),
                 dict(key="lu2020", doi="10.3201/eid2607.200764", access="full text (Europe PMC OA XML)")],
        exposure_type="single index, single lunch", exposure_duration_h=1.37, exposure_duration_note="index table present 82 min (12:01-13:23); overlap 53 min (table B), 75 min (table C; Lu 2020 gives 73 min), 23-82 min for others",
        room_dimensions="17 m x 8.1 m (average width) x 3.14 m; 431 m3 (Li 2021); '145 m2' (Lu 2020)", floor_area_m2=137.7, ceiling_height_m=3.14, volume_m3=431.0,
        geometry_note="table plan with seat positions in Li 2021 Fig. 1; distances index-to-infected up to 4.6 m; 1.55 m2 per patron",
        occupancy_n=89, ventilation="measured 0.56-0.77 ACH = 0.75-1.04 L/s per patron (tracer decay); 5 fan-coil units, no outdoor air supply",
        masks="none (dining)", index_case="1 patron (A1) at table A",
        n_exposed=79, n_infected=5, includes_index=False,
        attack_rate_reported="10/89 = 11.24% incl. table A; non-A tables 5/79; immediate neighbouring tables 5/16 (31.25%) vs remote tables 0/63; air-conditioning zone ABC 5/11 (45.45%) vs other zone 0/68",
        spatial_pattern="all infections inside one air-conditioning recirculation zone; none among 68 patrons elsewhere or 8 staff; not ordered by distance within the zone (the 2 patrons of table C closest to A were not infected)",
        other_groups="index's own table (family, travelled together): 4 of 9 others infected - excluded from the secondary attack rate",
        spatial_data_files=["data/li2021_restaurant_tables.csv", "data/spatial_strata.csv"], quality="A",
        quality_notes="Best-documented single event (video-verified seating, measured ventilation, per-table exposure times). Lu 2020 counts 83 customers + 8 staff = 91 persons; Li 2021 counts 89 patrons. Table-A infections cannot be separated from household/travel exposure.",
        derived=["floor_area_m2 = 17 x 8.1", "n_exposed = 89 - 10 (table A)"],
    ),
    dict(
        id="R2_jeonju_restaurant", scene="restaurant", analogue=True,
        setting="Restaurant, 9.2 m x 10.5 m, no windows or ventilation system, two ceiling air conditioners", location="Jeonju, South Korea",
        event_dates="2020-06-12", pathogen="SARS-CoV-2",
        sources=[dict(key="kwon2020", doi="10.3346/jkms.2020.35.e415", access="full text (Europe PMC OA XML)")],
        exposure_type="single index (visitor), single visit", exposure_duration_h=0.35, exposure_duration_note="overlaps of 5 min (case A) and 21 min (case C) with the infector",
        room_dimensions="9.2 m x 10.5 m", floor_area_m2=96.6, ceiling_height_m=None, volume_m3=None,
        geometry_note="air conditioners 3.2 m above floor; measured air speed 1.0-1.2 m/s along the infector-infectee path",
        occupancy_n=None, ventilation="no windows, no ventilation system; directed air-conditioner jet", masks="none while talking/eating",
        index_case="1 visitor (case B)", n_exposed=13, n_infected=2, includes_index=False,
        attack_rate_reported="15.4% (2/13)",
        spatial_pattern="both infectees downstream in the air-conditioner jet at 6.5 m (5 min) and 4.8 m (21 min); nobody outside the airflow path infected",
        other_groups=None, spatial_data_files=["data/spatial_strata.csv"], quality="A",
        quality_notes="CCTV-verified positions and timings. n = 13. Demonstrates directed (advective) long-range transmission in minutes.",
        derived=["exposure_duration_h = 21 min (longest overlap)"],
    ),
    dict(
        id="H1_skagit_choir", scene="choir", analogue=True,
        setting="Choir rehearsal in a church multipurpose hall; 6 rows x 20 chairs, half occupied", location="Skagit County, Washington, USA",
        event_dates="2020-03-10", pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="hamner2020", doi="10.15585/mmwr.mm6919e6", access="CDC MMWR page as an automated text extraction + abstract (Europe PMC)"),
                 dict(key="miller2021", doi="10.1111/ina.12751", access="accepted manuscript PDF (White Rose eprints 165690)")],
        exposure_type="single index, single 2.5-h rehearsal", exposure_duration_h=2.5, exposure_duration_note="40 min together, 50 min sectionals, 15 min break, 45 min together",
        room_dimensions="floor ~180 m2, mean ceiling height 4.5 m, 810 m3 (Miller 2021)", floor_area_m2=180.0, ceiling_height_m=4.5, volume_m3=810.0,
        geometry_note="chairs 6-10 in (15-25 cm) apart; nobody within 3 m in front of the index", occupancy_n=61,
        ventilation="estimated 0.3-1.0 h-1 (central estimate 0.7 h-1) from furnace heat balance; not measured", masks="none",
        index_case="1 symptomatic singer", n_exposed=60, n_infected=52, n_infected_alt=32, includes_index=False,
        attack_rate_reported="86.7% (52/60; 32 confirmed + 20 probable); 53.3% confirmed only (32/60)",
        spatial_pattern="'absence of any strong pattern in the spatial distribution of secondary cases' (Miller 2021); seat map withheld for privacy",
        other_groups=None, spatial_data_files=[], quality="A",
        quality_notes="20 of 52 cases are probable (symptom-based). Room volume from personal communication; ventilation inferred. Well-mixed benchmark: inferred emission 970 +/- 390 quanta/h.",
        derived=[],
    ),
    dict(
        id="H2_sydney_church", scene="choir", analogue=True,
        setting="Church services; chorister singing from a choir loft ~3-3.5 m above the congregation", location="Sydney, Australia", event_dates="2020-07-15..2020-07-17",
        pathogen="SARS-CoV-2",
        sources=[dict(key="katelaris2021", doi="10.3201/eid2706.210465", access="full text (Europe PMC OA XML)")],
        exposure_type="single index, four ~1-h services on 3 days", exposure_duration_h=1.0, exposure_duration_note="'four 1-hour services' (one each on 15 and 16 July, two on 17 July)",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note="circular church with high conical roof; seat positions from video",
        occupancy_n=None, ventilation="apex ventilation off, doors/windows largely closed, wall fans off ('minimal ventilation')", masks="none",
        index_case="1 chorister", n_exposed=508, n_infected=12, includes_index=False,
        attack_rate_reported="2.4% (12/508); 15 July 5/215 (2.3%); 16 July 7/120 (5.8%); 17 July (2 services) 0/173",
        spatial_pattern="all 12 secondary cases sat within one 70-degree sector, 1-15 m from (and below) the index; none in other sectors",
        other_groups=None, spatial_data_files=["data/spatial_strata.csv"], quality="B",
        quality_notes="85% of contacts tested. Sector denominators not reported, so the in-sector attack rate cannot be formed. 5 of 12 cases possibly household-acquired.",
        derived=[],
    ),
    # --------------------------------------------------- SCENE_DEFAULTS-CITED, OUT OF SCOPE
    dict(
        id="X1_diamond_princess", scene="out_of_scope", analogue=False,
        setting="Cruise ship under quarantine (3,711 passengers and crew)", location="Yokohama, Japan", event_dates="2020-01-20..2020-02-20",
        pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="mizumoto2020", doi="10.2807/1560-7917.ES.2020.25.10.2000180", access="full text (Europe PMC OA XML)")],
        exposure_type="multi-week, ship-wide, multi-generation, with intervention", exposure_duration_h=None, exposure_duration_note="weeks",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note=None, occupancy_n=3711,
        ventilation=None, masks=None, index_case="1 passenger who disembarked in Hong Kong", n_exposed=3711, n_infected=634, includes_index=True,
        attack_rate_reported="634 positive of 3,711 as at 20 Feb 2020 (17.1%); estimated asymptomatic proportion 17.9% (95% CrI 15.5-20.2%)",
        spatial_pattern="n/a", other_groups="712 cases in total by 1 March (per Furuse 2020)", spatial_data_files=[], quality="X",
        quality_notes="The paper gives 634/3,711 = 17.1% (17.9% is the asymptomatic proportion). Not one of the four scenes.",
        derived=["17.1% = 634/3711"],
    ),
    dict(
        id="X2_singapore_dormitories", scene="out_of_scope", analogue=False,
        setting="Purpose-built migrant-worker dormitories", location="Singapore", event_dates="2020-04..2020-05", pathogen="SARS-CoV-2 (ancestral)",
        sources=[dict(key="koh2020", doi="10.1136/oemed-2020-106626", access="full text (Europe PMC OA XML)")],
        exposure_type="months, residential, multi-generation", exposure_duration_h=None, exposure_duration_note="weeks to months",
        room_dimensions=None, floor_area_m2=None, ceiling_height_m=None, volume_m3=None, geometry_note=None, occupancy_n=295000,
        ventilation=None, masks=None, index_case=None, n_exposed=295000, n_infected=17758, includes_index=True,
        attack_rate_reported="17,758 confirmed cases among ~295,000 dormitory workers as of 6 May 2020 (6.0%); 'One dormitory housing approximately 13 000 workers had 19.4% of residents infected'; dormitory workers were 88% of national cases",
        spatial_pattern="n/a", other_groups=None, spatial_data_files=[], quality="X",
        quality_notes="The paper gives 17,758/295,000 = 6.0%; 88% is the share of national cases occurring in dormitory workers. Not one of the four scenes.",
        derived=["6.0% = 17758/295000"],
    ),
]

# Distance / zone strata (secondary cases among exposed, index excluded).
# d_min/d_max are distances from the index in metres where the source gives them; None otherwise.
STRATA = [
    # id, stratum label, d_min_m, d_max_m, n_exposed, n_infected, source key, note
    ("O1_seoul_callcentre", "north wing desks (digitized)", None, None, 137, 79, "park2020", "derived from Fig. 2; index position unknown; 84 of 94 cases have a seat in the figure"),
    ("O1_seoul_callcentre", "south wing desks (digitized)", None, None, 62, 4, "park2020", "derived from Fig. 2"),
    ("C1_marin_classroom", "front two rows (nearest teacher)", None, None, 10, 8, "lamhine2021", "desks 1.83 m apart"),
    ("C1_marin_classroom", "back three rows", None, None, 14, 4, "lamhine2021", "desks 1.83 m apart"),
    ("T1_zhejiang_bus", "rows 5-11 (within ~2 m of index row 8)", 0.0, 2.25, 33, 14, "shen2020", "row pitch 0.75 m; classification 1"),
    ("T1_zhejiang_bus", "rows 1-4 and 12-15", 2.25, 5.25, 34, 9, "shen2020", "classification 1"),
    ("T1_zhejiang_bus", "rows 6-10 (within 2 rows)", 0.0, 1.5, 23, 11, "shen2020", "classification 2 (alternative split of the same 67 passengers)"),
    ("T1_zhejiang_bus", "rows 1-5 and 11-15", 1.5, 5.25, 44, 12, "shen2020", "classification 2"),
    ("T2_hunan_coach", "rear seats rows 8-13 (index zone)", None, None, 19, 3, "ou2022", "Ou 2022 Table 1 (45 other passengers)"),
    ("T2_hunan_coach", "front seats rows 1-7", None, None, 26, 4, "ou2022", "Ou 2022 Table 1"),
    ("T5_vn54_flight", "business class, '≤2 seats away' (within ~2 m)", 0.0, 2.0, 12, 11, "khanh2020", "'within 2 meters ... approximated in business class to be <2 seats away'"),
    ("T5_vn54_flight", "business class, '>2 seats away'", 2.0, None, 8, 1, "khanh2020", ""),
    ("T5_vn54_flight", "premium economy (separate cabin)", None, None, 35, 0, "khanh2020", ""),
    ("T5_vn54_flight", "economy (separate cabin)", None, None, 145, 2, "khanh2020", "possibly unrelated infections"),
    ("R1_guangzhou_restaurant", "immediate neighbouring tables (TB, TC, T18)", 1.0, 4.6, 16, 5, "li2021", "table A excluded"),
    ("R1_guangzhou_restaurant", "remote tables (T04-T17)", None, None, 63, 0, "li2021", ""),
    ("R1_guangzhou_restaurant", "ABC air-conditioning zone, non-A tables (TB, TC)", 1.0, 4.6, 11, 5, "li2021", "alternative split of the same 79 patrons"),
    ("R1_guangzhou_restaurant", "other air-conditioning zones", None, None, 68, 0, "li2021", ""),
    ("R2_jeonju_restaurant", "in air-conditioner jet path, 4.8-6.5 m", 4.8, 6.5, None, 2, "kwon2020", "zone denominator not reported; 2/13 overall"),
    ("H2_sydney_church", "70-degree sector below index, 1-15 m", 1.0, 15.0, None, 12, "katelaris2021", "sector denominator not reported; 12/508 overall"),
    ("O4_german_meatplant", "fixed stations around index (all distances plotted)", 0.0, None, 78, 20, "guenther2020", "'>60%' within 8 m; counts in Appendix Table S2 not transcribed"),
    ("C2_jerusalem_highschool", "grades 7-9 (junior wing)", None, None, 581, 135, "steinzamir2020", "sum of 40/197 + 34/197 + 61/187"),
    ("C2_jerusalem_highschool", "grades 10-12 (senior wing)", None, None, 583, 18, "steinzamir2020", "sum of 9/200 + 6/195 + 3/188"),
    ("S1_liaocheng_supermarket", "employees (shift-long exposure)", None, None, 120, 11, "tian2021", "includes primary case(s)"),
    ("S1_liaocheng_supermarket", "customers (short visits)", None, None, 8224, 0, "tian2021", ""),
]

# Hu et al. 2021 (Clin Infect Dis) Table 1: attack rate (%) by rows apart x columns apart.
# As rendered on the publisher page the five same-row values sit under the headers
# "Same column, 1, 2, 3, 4" with "5" empty.  A passenger cannot be 0 rows AND 0 columns away
# from the index, the text calls 3.53% the *adjacent-seat* rate, and the printed column means
# (0.17, 0.68, 0.41, 0.16, 0.12, 0.13) are only reproducible if the same-row values belong to
# columns 1..5.  We therefore store them under columns 1..5 and flag the realignment.
HU_TRAIN = dict(
    rows_apart=[0, 1, 2, 3],
    cols_apart=[0, 1, 2, 3, 4, 5],
    attack_pct=[
        [None, 3.53, 1.65, 0.38, 0.38, 0.29],
        [0.21, 0.24, 0.14, 0.09, 0.03, 0.05],
        [0.25, 0.17, 0.23, 0.16, 0.09, 0.17],
        [0.05, 0.05, 0.13, 0.10, 0.10, 0.06],
    ],
    ci_low=[
        [None, 2.89, 1.18, 0.18, 0.19, 0.10],
        [0.11, 0.14, 0.06, 0.03, 0.00, 0.00],
        [0.14, 0.09, 0.12, 0.07, 0.03, 0.06],
        [0.01, 0.01, 0.05, 0.03, 0.03, 0.00],
    ],
    ci_high=[
        [None, 4.31, 2.31, 0.78, 0.79, 0.85],
        [0.38, 0.41, 0.32, 0.25, 0.16, 0.30],
        [0.45, 0.33, 0.46, 0.36, 0.27, 0.50],
        [0.18, 0.17, 0.33, 0.30, 0.30, 0.36],
    ],
    row_mean_pct=[1.53, 0.14, 0.18, 0.08],
    col_mean_pct=[0.17, 0.68, 0.41, 0.16, 0.12, 0.13],
    overall_pct=0.32,
    per_hour_increase_pct=dict(overall=0.15, adjacent=1.3, same_row_other=0.26, one_row=0.10, two_rows=0.09, three_rows=0.04),
    seat_width_m=0.5, row_pitch_m_reported=0.4,
)

# Li et al. 2021 (Build Environ) Tables 1 and 3: per-table patrons, cases, overlap with table A,
# total exposure time, normalised predicted exposure to droplet nuclei (CFD) and measured tracer.
LI_RESTAURANT = [
    # table, patrons, infected, overlap_with_A_min, total_exposure_min, norm_meas_tracer, norm_pred_tracer, norm_pred_exposure
    ("TA", 10, 5, 82, 82, 1.00, 1.00, 1.00),
    ("TB", 4, 3, 53, 53, 0.87, 1.04, 0.76),
    ("TC", 7, 2, 75, 77, 0.98, 0.93, 0.89),
    ("T04", 0, 0, None, None, None, 1.00, 0.00),
    ("T05", 2, 0, 52, 52, None, 0.62, 0.07),
    ("T06", 4, 0, 82, 82, None, 0.47, 0.13),
    ("T07", 3, 0, 69, 69, None, 0.42, 0.04),
    ("T08", 2, 0, 55, 69, None, 0.42, 0.06),
    ("T09", 10, 0, 75, 75, None, 0.32, 0.04),
    ("T10", 6, 0, 82, 82, 0.55, 0.52, 0.08),
    ("T11", 7, 0, 70, 70, None, 0.57, 0.12),
    ("T12", 2, 0, 64, 64, None, 0.50, 0.09),
    ("T13", 6, 0, 50, 50, None, 0.55, 0.05),
    ("T14", 3, 0, 61, 61, None, 0.63, 0.11),
    ("T15", 8, 0, 82, 89, 0.58, 0.54, 0.23),
    ("T16", 5, 0, 48, 48, 0.70, 0.56, 0.06),
    ("T17", 5, 0, 23, 79, 0.86, 0.75, 0.47),
    ("T18", 5, 0, 77, 77, 0.73, 0.85, 0.40),
]

# Seoul call centre epidemic curve, digitized from Park et al. 2020 Fig. 1 (one square = one case,
# by date of symptom onset; asymptomatic cases excluded by the authors).
CALLCENTRE_EPICURVE = [
    # date, 11th floor, 10th floor, 9th floor
    ("2020-02-22", 0, 1, 0), ("2020-02-25", 1, 0, 0), ("2020-02-28", 3, 0, 0), ("2020-02-29", 1, 1, 0),
    ("2020-03-01", 1, 0, 0), ("2020-03-02", 2, 0, 1), ("2020-03-04", 3, 0, 0), ("2020-03-05", 7, 0, 0),
    ("2020-03-06", 16, 0, 0), ("2020-03-07", 14, 0, 0), ("2020-03-08", 12, 0, 0), ("2020-03-09", 16, 0, 0),
    ("2020-03-11", 2, 0, 0), ("2020-03-12", 0, 1, 0), ("2020-03-13", 1, 0, 0), ("2020-03-14", 1, 0, 0),
    ("2020-03-15", 2, 0, 0), ("2020-03-16", 2, 0, 0), ("2020-03-19", 1, 0, 0), ("2020-03-20", 1, 0, 0),
]
